name: skd
dependencies:
  - python=3.6
  - pytorch==1.3.1
  - torchvision
  - numpy
  - matplotlib
  - pillow==6.1
  - pip
  - pip:
    - segmentation_models_pytorch
    - comet_ml
    - opencv-python
    - fastai==1.0.60
