cd ..
mkdir saved_models/
mkdir saved_models/camvid/

mkdir saved_models/camvid/less_data10/

mkdir saved_models/camvid/less_data10/resnet10/
mkdir saved_models/camvid/less_data10/resnet10/classifier/
mkdir saved_models/camvid/less_data10/resnet10/stage0/
mkdir saved_models/camvid/less_data10/resnet10/stage1/
mkdir saved_models/camvid/less_data10/resnet10/stage2/
mkdir saved_models/camvid/less_data10/resnet10/stage3/
mkdir saved_models/camvid/less_data10/resnet10/stage4/
mkdir saved_models/camvid/less_data10/resnet10/stage5/
mkdir saved_models/camvid/less_data10/resnet10/stage6/
mkdir saved_models/camvid/less_data10/resnet10/stage7/
mkdir saved_models/camvid/less_data10/resnet10/stage8/
mkdir saved_models/camvid/less_data10/resnet10/stage9/

mkdir saved_models/camvid/less_data10/resnet14/
mkdir saved_models/camvid/less_data10/resnet14/classifier/
mkdir saved_models/camvid/less_data10/resnet14/stage0/
mkdir saved_models/camvid/less_data10/resnet14/stage1/
mkdir saved_models/camvid/less_data10/resnet14/stage2/
mkdir saved_models/camvid/less_data10/resnet14/stage3/
mkdir saved_models/camvid/less_data10/resnet14/stage4/
mkdir saved_models/camvid/less_data10/resnet14/stage5/
mkdir saved_models/camvid/less_data10/resnet14/stage6/
mkdir saved_models/camvid/less_data10/resnet14/stage7/
mkdir saved_models/camvid/less_data10/resnet14/stage8/
mkdir saved_models/camvid/less_data10/resnet14/stage9/

mkdir saved_models/camvid/less_data10/resnet18/
mkdir saved_models/camvid/less_data10/resnet18/classifier/
mkdir saved_models/camvid/less_data10/resnet18/stage0/
mkdir saved_models/camvid/less_data10/resnet18/stage1/
mkdir saved_models/camvid/less_data10/resnet18/stage2/
mkdir saved_models/camvid/less_data10/resnet18/stage3/
mkdir saved_models/camvid/less_data10/resnet18/stage4/
mkdir saved_models/camvid/less_data10/resnet18/stage5/
mkdir saved_models/camvid/less_data10/resnet18/stage6/
mkdir saved_models/camvid/less_data10/resnet18/stage7/
mkdir saved_models/camvid/less_data10/resnet18/stage8/
mkdir saved_models/camvid/less_data10/resnet18/stage9/

mkdir saved_models/camvid/less_data10/resnet20/
mkdir saved_models/camvid/less_data10/resnet20/classifier/
mkdir saved_models/camvid/less_data10/resnet20/stage0/
mkdir saved_models/camvid/less_data10/resnet20/stage1/
mkdir saved_models/camvid/less_data10/resnet20/stage2/
mkdir saved_models/camvid/less_data10/resnet20/stage3/
mkdir saved_models/camvid/less_data10/resnet20/stage4/
mkdir saved_models/camvid/less_data10/resnet20/stage5/
mkdir saved_models/camvid/less_data10/resnet20/stage6/
mkdir saved_models/camvid/less_data10/resnet20/stage7/
mkdir saved_models/camvid/less_data10/resnet20/stage8/
mkdir saved_models/camvid/less_data10/resnet20/stage9/

mkdir saved_models/camvid/less_data10/resnet26/
mkdir saved_models/camvid/less_data10/resnet26/classifier/
mkdir saved_models/camvid/less_data10/resnet26/stage0/
mkdir saved_models/camvid/less_data10/resnet26/stage1/
mkdir saved_models/camvid/less_data10/resnet26/stage2/
mkdir saved_models/camvid/less_data10/resnet26/stage3/
mkdir saved_models/camvid/less_data10/resnet26/stage4/
mkdir saved_models/camvid/less_data10/resnet26/stage5/
mkdir saved_models/camvid/less_data10/resnet26/stage6/
mkdir saved_models/camvid/less_data10/resnet26/stage7/
mkdir saved_models/camvid/less_data10/resnet26/stage8/
mkdir saved_models/camvid/less_data10/resnet26/stage9/

mkdir saved_models/camvid/less_data20/

mkdir saved_models/camvid/less_data20/resnet10/
mkdir saved_models/camvid/less_data20/resnet10/classifier/
mkdir saved_models/camvid/less_data20/resnet10/stage0/
mkdir saved_models/camvid/less_data20/resnet10/stage1/
mkdir saved_models/camvid/less_data20/resnet10/stage2/
mkdir saved_models/camvid/less_data20/resnet10/stage3/
mkdir saved_models/camvid/less_data20/resnet10/stage4/
mkdir saved_models/camvid/less_data20/resnet10/stage5/
mkdir saved_models/camvid/less_data20/resnet10/stage6/
mkdir saved_models/camvid/less_data20/resnet10/stage7/
mkdir saved_models/camvid/less_data20/resnet10/stage8/
mkdir saved_models/camvid/less_data20/resnet10/stage9/

mkdir saved_models/camvid/less_data20/resnet14/
mkdir saved_models/camvid/less_data20/resnet14/classifier/
mkdir saved_models/camvid/less_data20/resnet14/stage0/
mkdir saved_models/camvid/less_data20/resnet14/stage1/
mkdir saved_models/camvid/less_data20/resnet14/stage2/
mkdir saved_models/camvid/less_data20/resnet14/stage3/
mkdir saved_models/camvid/less_data20/resnet14/stage4/
mkdir saved_models/camvid/less_data20/resnet14/stage5/
mkdir saved_models/camvid/less_data20/resnet14/stage6/
mkdir saved_models/camvid/less_data20/resnet14/stage7/
mkdir saved_models/camvid/less_data20/resnet14/stage8/
mkdir saved_models/camvid/less_data20/resnet14/stage9/

mkdir saved_models/camvid/less_data20/resnet18/
mkdir saved_models/camvid/less_data20/resnet18/classifier/
mkdir saved_models/camvid/less_data20/resnet18/stage0/
mkdir saved_models/camvid/less_data20/resnet18/stage1/
mkdir saved_models/camvid/less_data20/resnet18/stage2/
mkdir saved_models/camvid/less_data20/resnet18/stage3/
mkdir saved_models/camvid/less_data20/resnet18/stage4/
mkdir saved_models/camvid/less_data20/resnet18/stage5/
mkdir saved_models/camvid/less_data20/resnet18/stage6/
mkdir saved_models/camvid/less_data20/resnet18/stage7/
mkdir saved_models/camvid/less_data20/resnet18/stage8/
mkdir saved_models/camvid/less_data20/resnet18/stage9/

mkdir saved_models/camvid/less_data20/resnet20/
mkdir saved_models/camvid/less_data20/resnet20/classifier/
mkdir saved_models/camvid/less_data20/resnet20/stage0/
mkdir saved_models/camvid/less_data20/resnet20/stage1/
mkdir saved_models/camvid/less_data20/resnet20/stage2/
mkdir saved_models/camvid/less_data20/resnet20/stage3/
mkdir saved_models/camvid/less_data20/resnet20/stage4/
mkdir saved_models/camvid/less_data20/resnet20/stage5/
mkdir saved_models/camvid/less_data20/resnet20/stage6/
mkdir saved_models/camvid/less_data20/resnet20/stage7/
mkdir saved_models/camvid/less_data20/resnet20/stage8/
mkdir saved_models/camvid/less_data20/resnet20/stage9/

mkdir saved_models/camvid/less_data20/resnet26/
mkdir saved_models/camvid/less_data20/resnet26/classifier/
mkdir saved_models/camvid/less_data20/resnet26/stage0/
mkdir saved_models/camvid/less_data20/resnet26/stage1/
mkdir saved_models/camvid/less_data20/resnet26/stage2/
mkdir saved_models/camvid/less_data20/resnet26/stage3/
mkdir saved_models/camvid/less_data20/resnet26/stage4/
mkdir saved_models/camvid/less_data20/resnet26/stage5/
mkdir saved_models/camvid/less_data20/resnet26/stage6/
mkdir saved_models/camvid/less_data20/resnet26/stage7/
mkdir saved_models/camvid/less_data20/resnet26/stage8/
mkdir saved_models/camvid/less_data20/resnet26/stage9/

mkdir saved_models/camvid/less_data30/

mkdir saved_models/camvid/less_data30/resnet10/
mkdir saved_models/camvid/less_data30/resnet10/classifier/
mkdir saved_models/camvid/less_data30/resnet10/stage0/
mkdir saved_models/camvid/less_data30/resnet10/stage1/
mkdir saved_models/camvid/less_data30/resnet10/stage2/
mkdir saved_models/camvid/less_data30/resnet10/stage3/
mkdir saved_models/camvid/less_data30/resnet10/stage4/
mkdir saved_models/camvid/less_data30/resnet10/stage5/
mkdir saved_models/camvid/less_data30/resnet10/stage6/
mkdir saved_models/camvid/less_data30/resnet10/stage7/
mkdir saved_models/camvid/less_data30/resnet10/stage8/
mkdir saved_models/camvid/less_data30/resnet10/stage9/

mkdir saved_models/camvid/less_data30/resnet14/
mkdir saved_models/camvid/less_data30/resnet14/classifier/
mkdir saved_models/camvid/less_data30/resnet14/stage0/
mkdir saved_models/camvid/less_data30/resnet14/stage1/
mkdir saved_models/camvid/less_data30/resnet14/stage2/
mkdir saved_models/camvid/less_data30/resnet14/stage3/
mkdir saved_models/camvid/less_data30/resnet14/stage4/
mkdir saved_models/camvid/less_data30/resnet14/stage5/
mkdir saved_models/camvid/less_data30/resnet14/stage6/
mkdir saved_models/camvid/less_data30/resnet14/stage7/
mkdir saved_models/camvid/less_data30/resnet14/stage8/
mkdir saved_models/camvid/less_data30/resnet14/stage9/

mkdir saved_models/camvid/less_data30/resnet18/
mkdir saved_models/camvid/less_data30/resnet18/classifier/
mkdir saved_models/camvid/less_data30/resnet18/stage0/
mkdir saved_models/camvid/less_data30/resnet18/stage1/
mkdir saved_models/camvid/less_data30/resnet18/stage2/
mkdir saved_models/camvid/less_data30/resnet18/stage3/
mkdir saved_models/camvid/less_data30/resnet18/stage4/
mkdir saved_models/camvid/less_data30/resnet18/stage5/
mkdir saved_models/camvid/less_data30/resnet18/stage6/
mkdir saved_models/camvid/less_data30/resnet18/stage7/
mkdir saved_models/camvid/less_data30/resnet18/stage8/
mkdir saved_models/camvid/less_data30/resnet18/stage9/

mkdir saved_models/camvid/less_data30/resnet20/
mkdir saved_models/camvid/less_data30/resnet20/classifier/
mkdir saved_models/camvid/less_data30/resnet20/stage0/
mkdir saved_models/camvid/less_data30/resnet20/stage1/
mkdir saved_models/camvid/less_data30/resnet20/stage2/
mkdir saved_models/camvid/less_data30/resnet20/stage3/
mkdir saved_models/camvid/less_data30/resnet20/stage4/
mkdir saved_models/camvid/less_data30/resnet20/stage5/
mkdir saved_models/camvid/less_data30/resnet20/stage6/
mkdir saved_models/camvid/less_data30/resnet20/stage7/
mkdir saved_models/camvid/less_data30/resnet20/stage8/
mkdir saved_models/camvid/less_data30/resnet20/stage9/

mkdir saved_models/camvid/less_data30/resnet26/
mkdir saved_models/camvid/less_data30/resnet26/classifier/
mkdir saved_models/camvid/less_data30/resnet26/stage0/
mkdir saved_models/camvid/less_data30/resnet26/stage1/
mkdir saved_models/camvid/less_data30/resnet26/stage2/
mkdir saved_models/camvid/less_data30/resnet26/stage3/
mkdir saved_models/camvid/less_data30/resnet26/stage4/
mkdir saved_models/camvid/less_data30/resnet26/stage5/
mkdir saved_models/camvid/less_data30/resnet26/stage6/
mkdir saved_models/camvid/less_data30/resnet26/stage7/
mkdir saved_models/camvid/less_data30/resnet26/stage8/
mkdir saved_models/camvid/less_data30/resnet26/stage9/

mkdir saved_models/camvid/less_data40/

mkdir saved_models/camvid/less_data40/resnet10/
mkdir saved_models/camvid/less_data40/resnet10/classifier/
mkdir saved_models/camvid/less_data40/resnet10/stage0/
mkdir saved_models/camvid/less_data40/resnet10/stage1/
mkdir saved_models/camvid/less_data40/resnet10/stage2/
mkdir saved_models/camvid/less_data40/resnet10/stage3/
mkdir saved_models/camvid/less_data40/resnet10/stage4/
mkdir saved_models/camvid/less_data40/resnet10/stage5/
mkdir saved_models/camvid/less_data40/resnet10/stage6/
mkdir saved_models/camvid/less_data40/resnet10/stage7/
mkdir saved_models/camvid/less_data40/resnet10/stage8/
mkdir saved_models/camvid/less_data40/resnet10/stage9/

mkdir saved_models/camvid/less_data40/resnet14/
mkdir saved_models/camvid/less_data40/resnet14/classifier/
mkdir saved_models/camvid/less_data40/resnet14/stage0/
mkdir saved_models/camvid/less_data40/resnet14/stage1/
mkdir saved_models/camvid/less_data40/resnet14/stage2/
mkdir saved_models/camvid/less_data40/resnet14/stage3/
mkdir saved_models/camvid/less_data40/resnet14/stage4/
mkdir saved_models/camvid/less_data40/resnet14/stage5/
mkdir saved_models/camvid/less_data40/resnet14/stage6/
mkdir saved_models/camvid/less_data40/resnet14/stage7/
mkdir saved_models/camvid/less_data40/resnet14/stage8/
mkdir saved_models/camvid/less_data40/resnet14/stage9/

mkdir saved_models/camvid/less_data40/resnet18/
mkdir saved_models/camvid/less_data40/resnet18/classifier/
mkdir saved_models/camvid/less_data40/resnet18/stage0/
mkdir saved_models/camvid/less_data40/resnet18/stage1/
mkdir saved_models/camvid/less_data40/resnet18/stage2/
mkdir saved_models/camvid/less_data40/resnet18/stage3/
mkdir saved_models/camvid/less_data40/resnet18/stage4/
mkdir saved_models/camvid/less_data40/resnet18/stage5/
mkdir saved_models/camvid/less_data40/resnet18/stage6/
mkdir saved_models/camvid/less_data40/resnet18/stage7/
mkdir saved_models/camvid/less_data40/resnet18/stage8/
mkdir saved_models/camvid/less_data40/resnet18/stage9/

mkdir saved_models/camvid/less_data40/resnet20/
mkdir saved_models/camvid/less_data40/resnet20/classifier/
mkdir saved_models/camvid/less_data40/resnet20/stage0/
mkdir saved_models/camvid/less_data40/resnet20/stage1/
mkdir saved_models/camvid/less_data40/resnet20/stage2/
mkdir saved_models/camvid/less_data40/resnet20/stage3/
mkdir saved_models/camvid/less_data40/resnet20/stage4/
mkdir saved_models/camvid/less_data40/resnet20/stage5/
mkdir saved_models/camvid/less_data40/resnet20/stage6/
mkdir saved_models/camvid/less_data40/resnet20/stage7/
mkdir saved_models/camvid/less_data40/resnet20/stage8/
mkdir saved_models/camvid/less_data40/resnet20/stage9/

mkdir saved_models/camvid/less_data40/resnet26/
mkdir saved_models/camvid/less_data40/resnet26/classifier/
mkdir saved_models/camvid/less_data40/resnet26/stage0/
mkdir saved_models/camvid/less_data40/resnet26/stage1/
mkdir saved_models/camvid/less_data40/resnet26/stage2/
mkdir saved_models/camvid/less_data40/resnet26/stage3/
mkdir saved_models/camvid/less_data40/resnet26/stage4/
mkdir saved_models/camvid/less_data40/resnet26/stage5/
mkdir saved_models/camvid/less_data40/resnet26/stage6/
mkdir saved_models/camvid/less_data40/resnet26/stage7/
mkdir saved_models/camvid/less_data40/resnet26/stage8/
mkdir saved_models/camvid/less_data40/resnet26/stage9/