cp /home/navid/.fastai/data/imagenette/train/n01440764/* /home/navid/.fastai/data/imagenette/train_images 
cp /home/navid/.fastai/data/imagenette/train/n03028079/* /home/navid/.fastai/data/imagenette/train_images 
cp /home/navid/.fastai/data/imagenette/train/n03888257/* /home/navid/.fastai/data/imagenette/train_images 
cp /home/navid/.fastai/data/imagenette/train/n03000684/* /home/navid/.fastai/data/imagenette/train_images 
cp /home/navid/.fastai/data/imagenette/train/n02102040/* /home/navid/.fastai/data/imagenette/train_images 
cp /home/navid/.fastai/data/imagenette/train/n03417042/* /home/navid/.fastai/data/imagenette/train_images 
cp /home/navid/.fastai/data/imagenette/train/n03445777/* /home/navid/.fastai/data/imagenette/train_images 
cp /home/navid/.fastai/data/imagenette/train/n03394916/* /home/navid/.fastai/data/imagenette/train_images 
cp /home/navid/.fastai/data/imagenette/train/n03425413/* /home/navid/.fastai/data/imagenette/train_images 
cp /home/navid/.fastai/data/imagenette/train/n02979186/* /home/navid/.fastai/data/imagenette/train_images 
cp /home/navid/.fastai/data/imagenette/val/n01440764/* /home/navid/.fastai/data/imagenette/val_images 
cp /home/navid/.fastai/data/imagenette/val/n03028079/* /home/navid/.fastai/data/imagenette/val_images 
cp /home/navid/.fastai/data/imagenette/val/n03888257/* /home/navid/.fastai/data/imagenette/val_images 
cp /home/navid/.fastai/data/imagenette/val/n03000684/* /home/navid/.fastai/data/imagenette/val_images 
cp /home/navid/.fastai/data/imagenette/val/n02102040/* /home/navid/.fastai/data/imagenette/val_images 
cp /home/navid/.fastai/data/imagenette/val/n03417042/* /home/navid/.fastai/data/imagenette/val_images 
cp /home/navid/.fastai/data/imagenette/val/n03445777/* /home/navid/.fastai/data/imagenette/val_images 
cp /home/navid/.fastai/data/imagenette/val/n03394916/* /home/navid/.fastai/data/imagenette/val_images 
cp /home/navid/.fastai/data/imagenette/val/n03425413/* /home/navid/.fastai/data/imagenette/val_images 
cp /home/navid/.fastai/data/imagenette/val/n02979186/* /home/navid/.fastai/data/imagenette/val_images 
